apiVersion: v1
kind: Service
metadata:
  name: kongsbergvitensenter
  namespace: prod
spec:
  type: NodePort
  selector:
    app: kongsbergvitensenter
  ports:
    - port: 4173
      targetPort: 4173
      nodePort: 30083
