apiVersion: apps/v1
kind: Deployment
metadata:
  name: visithammerfest-api
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visithammerfest-api
  template:
    metadata:
      labels:
        app: visithammerfest-api
    spec:
      containers:
        - name: api
          image: localhost:32000/visithammerfest-api:latest
          ports:
            - containerPort: 5170
          envFrom:
            - secretRef:
                name: visithammerfest-secret
          volumeMounts:
            - name: uploads
              mountPath: /app/server/uploads
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
      volumes:
        - name: uploads
          hostPath:
            path: /home/wegener/containers/visithammerfest/server/uploads
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: visithammerfest-api
  namespace: prod
spec:
  type: NodePort
  selector:
    app: visithammerfest-api
  ports:
    - port: 5170
      targetPort: 5170
      nodePort: 30085
