apiVersion: v1
kind: Service
metadata:
  name: piratehusky
  namespace: prod
spec:
  type: NodePort
  selector:
    app: piratehusky
  ports:
    - port: 4173
      targetPort: 4173
      nodePort: 30082
