apiVersion: apps/v1
kind: Deployment
metadata:
  name: wegener-auth
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wegener-auth
  template:
    metadata:
      labels:
        app: wegener-auth
    spec:
      initContainers:
        - name: migrate
          image: localhost:32000/wegener-auth:latest
          command: ["node_modules/.bin/prisma", "db", "push", "--schema", "server/prisma/schema.prisma", "--accept-data-loss"]
          envFrom:
            - secretRef:
                name: wegener-auth-secret
      containers:
        - name: api
          image: localhost:32000/wegener-auth:latest
          ports:
            - containerPort: 3010
          envFrom:
            - secretRef:
                name: wegener-auth-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "384Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: wegener-auth
  namespace: prod
spec:
  type: NodePort
  selector:
    app: wegener-auth
  ports:
    - port: 3010
      targetPort: 3010
      nodePort: 30089
