services:
  db:
    image: postgres:16
    container_name: wegener-portal-postgres
    environment:
      POSTGRES_DB: wegener_portal
      POSTGRES_USER: wegener
      POSTGRES_PASSWORD: wegener
    ports:
      - '5441:5432'
    volumes:
      - ./server/data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wegener-api
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - '3011:3011'
    networks:
      - default
      - web
    restart: unless-stopped

  web:
    build: .
    container_name: wegener.no
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - web

networks:
  web:
    external: true
