server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: "/(.*)"
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
      - source_labels: [__meta_docker_container_label_traefik_router]
        target_label: traefik_router
      - source_labels: [__meta_docker_container_label_traefik_port]
        target_label: traefik_port
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{compose_service=~"traefik|.*traefik.*",container=~".*traefik.*"}'
          stages:
            - json:
                expressions:
                  router: RouterName
                  entrypoint: EntryPointName
                  method: RequestMethod
                  status: DownstreamStatus
                  client_ip: OriginIP
                  host: RequestHost
            - labels:
                router: ""
                entrypoint: ""
                method: ""
                status: ""
                client_ip: ""
                host: ""

  - job_name: traefik_access_log
    static_configs:
      - targets: [localhost]
        labels:
          __path__: /var/log/traefik/traefik-access.log
          job: traefik-file
    pipeline_stages:
      - json:
          expressions:
            router: RouterName
            entrypoint: EntryPointName
            method: RequestMethod
            status: DownstreamStatus
            client_ip: OriginIP
            host: RequestHost
      - labels:
          router: ""
          entrypoint: ""
          method: ""
          status: ""
          client_ip: ""
          host: ""
